### ISSUE TITLE
Dont save file names (strings in CSV) to DB when using with AjaxUpload

### ISSUE THREAD

**Issue by lapp** [Jako/FormIt2db#9]
Hi Jako,

first many thanks for your work on MODx!

Found issue:
When using Formit2DB with AjaxUpload I cant save the file names to DB. Consider this Formit call:

```
[[!FormIt?
   &hooks=`AjaxUpload2Formit,AjaxUploadAttachments,FormItSaveForm,Formit2db,email,FormItAutoResponder,redirect`
   &ajaxuploadFieldname=`filesCSV`
   &arrayFields=`["filesCSV"]`
   ...
   &store=`1`
   &redirectTo=`6822`
]]
```

```
<form action="[[~[[*id]]]]" method="post" class="form-horizontal" id="reklamacni-formular">
...
<input type="text" id="filesCSV" name="filesCSV" hidden="hidden">
...
</form>
```

After submit, string content of "filesCSV" is available in all other hooks (FormItSaveForm, email, FormItAutoResponder, redirect) except for Formit2db.

- All other fileds in the form works well and are being stored with Formit2db (and all other hooks)
- No errors in MODx neither in PHP log

Would you be so kind and try to check it, please?

Thanks and regards, Mike

**Comment by lapp** [comment]
Update: 
It does not work only when using "schema alias key" as name of the input field. When using "schema field key" (DB column name) it works!
But again: using "schema alias key" for all other input fields except "ajaxuploadFieldname" works well

**Comment by lapp** [comment]
Update2:
My mistake, **you cant use &arrayFields=["filesCSV"]**.
Now everything works as expected!

**Comment by Jako** [comment]
Yes, you have to use

```
   &arrayFields=`filesCSV`
```

**Comment by lapp** [comment]
No, its the other way round :-) You can’t use &arrayFields=`filesCSV`When you use it, it doesn’t  work.
